### ISSUE TITLE
criar o logout no front

### ISSUE THREAD

**Issue by aguedamaiara** [PDSC-ReglusAcademy/FrontEnd-ReglusAcademy#2]
# Realizar Logout

### User Story

**Título:** Realizar Logout

**Como** um usuário autenticado

**Eu quero** fazer logout do sistema

**Para que** eu possa encerrar minha sessão com segurança.

### Critérios de Aceitação

1. **Logout:**
    - O sistema deve permitir que o usuário faça logout a partir de qualquer página autenticada.
    - O sistema deve encerrar a sessão do usuário de forma segura.
2. **Redirecionamento:**
    - Após o logout, o sistema deve redirecionar o usuário para a página de login ou a página inicial pública.
3. **Confirmação:**
    - O sistema deve exibir uma mensagem confirmando que o logout foi realizado com sucesso.

### Cenários de Uso

**Cenário 1: Logout bem sucedido**

**Dado que** um usuário autenticado está em uma página qualquer do sistema

**Quando** clica no botão de logout

**Então** o sistema deve encerrar a sessão do usuário

**E** redirecionar o usuário para a página de login

**E** exibir uma mensagem de confirmação de logout.

**Cenário 2: Logout a partir do dashboard**

**Dado que** um usuário autenticado está na página do dashboard

**Quando** clica no botão de logout

**Então** o sistema deve encerrar a sessão do usuário

**E** redirecionar o usuário para a página de login

**E** exibir uma mensagem de confirmação de logout.

**Cenário 3: Logout a partir de uma página de perfil**

**Dado que** um usuário autenticado está na página de perfil

**Quando** clica no botão de logout

**Então** o sistema deve encerrar a sessão do usuário

**E** redirecionar o usuário para a página de login

**E** exibir uma mensagem de confirmação de logout.

**Cenário 4: Tentativa de acessar página autenticada após logout**

**Dado que** um usuário fez logout do sistema

**Quando** tenta acessar uma página que requer autenticação

**Então** o sistema deve redirecionar o usuário para a página de login

**E** exibir uma mensagem informando que o acesso requer autenticação.

**Comment by williemoliveiraa** [comment]
Opção de Logout Criada.
